version: 0.1

phases:
  install:
    commands:
      - echo Installing build dependencies...
      - npm run preinstall
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm run prebuild
  build:
    commands:
      - echo Build started on `date`
      - npm run pack
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/highlow.zip